version: "3.8"

services:

  web:
    build: 
      context: ./php
    volumes:
      - ./testProject:/var/www/app
  
  nginx:
    image: nginx:latest
    volumes:
      - ./testProject:/var/www/app
      - ./nginx/config:/etc/nginx/conf.d
    working_dir: /var/www/app
    ports:
      - 4888:80
    depends_on:
      - web

  composer:
    image: composer:2.0.11
    volumes:
      - ./testProject:/var/www/app
    working_dir: /var/www/app
    command: composer install
